# Generated by Django 5.2.6 on 2025-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="quarter",
            field=models.IntegerField(default=1),
        ),
    ]
