# Generated by Django 5.2.6 on 2025-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_quarter"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.IntegerField(default=1),
        ),
    ]
