# Generated by Django 5.2.6 on 2025-10-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motiontype",
            name="max_dtw_distance",
        ),
        migrations.AddField(
            model_name="motionrecording",
            name="device_category",
            field=models.CharField(
                choices=[("lip_motion", "립모션"), ("gloves", "장갑")],
                default="gloves",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="motiontype",
            name="max_dtw_distances",
            field=models.JSONField(
                default=dict,
                help_text="장비별 최대 DTW 거리 (예: {'gloves': 123, 'lip_motion': 456})",
            ),
        ),
        migrations.AddField(
            model_name="userrecording",
            name="device_category",
            field=models.CharField(
                choices=[("lip_motion", "립모션"), ("gloves", "장갑")],
                default="gloves",
                max_length=20,
            ),
        ),
    ]
