# Generated by Django 5.2.6 on 2025-10-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_remove_motiontype_max_dtw_distance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motionrecording",
            name="device_category",
        ),
        migrations.RemoveField(
            model_name="motiontype",
            name="max_dtw_distances",
        ),
        migrations.RemoveField(
            model_name="userrecording",
            name="device_category",
        ),
        migrations.AddField(
            model_name="motiontype",
            name="max_dtw_distance",
            field=models.FloatField(
                default=1000.0, help_text="점수 정규화를 위한 최대 DTW 거리"
            ),
        ),
    ]
